import type {Metadata} from 'next';
import {Arrow} from '@/components/ui';
import SchoolPreview from '@/components/school-preview';
import SchoolPortals from '@/components/school-portals';
import {schoolModules,schoolPrinting} from '@/lib/school-setu';
import {Users,BookOpen,CalendarDays,ClipboardCheck,Wallet,GraduationCap,Receipt,Library,Bus,Megaphone,BarChart3,ShieldCheck,ArrowDown} from 'lucide-react';
export const metadata:Metadata={title:'School Setu ERP',description:'School Setu connects admissions, academics, attendance, fees, payroll and campus operations with principal, teacher and parent portals. Explore features and printing availability.'};
const icons={Users,BookOpen,CalendarDays,ClipboardCheck,Wallet,GraduationCap,Receipt,Library,Bus,Megaphone,BarChart3,ShieldCheck};
export default function SchoolSetu(){return <main id="main" className="product-page"><section className="product-hero"><div className="container product-hero-grid"><div><div className="eyebrow">SCHOOL SETU / BY LAVENER HOLDINGS</div><h1>From admission<br/>to <em>achievement.</em></h1><p>One connected workspace for students, academics, campus teams, fees, and families.</p><div className="hero-actions"><a href="/#contact" className="button button-gold">Discuss School Setu <Arrow diagonal/></a><a href="#modules" className="text-link">Explore the modules <ArrowDown size={16}/></a></div><div className="product-audience">For principals. For teachers. For parents.</div></div><div className="product-hero-preview"><SchoolPreview/></div></div></section><div className="product-jump-nav"><nav className="container" aria-label="School Setu sections"><a href="#portals">Three portals</a><a href="#modules">School modules</a><a href="#results">Result workflow</a><a href="#printing">Print formats</a></nav></div>
<section className="section container" id="portals"><div className="section-heading"><div><div className="eyebrow">ONE SCHOOL / THREE CONNECTED VIEWS</div><h2>The right workspace<br/><em>for every role.</em></h2></div><p>Leadership, classroom work, and family visibility connect through role-aware access.</p></div><SchoolPortals/></section>
<section className="product-modules-section" id="modules"><div className="container"><div className="section-heading"><div><div className="eyebrow">ACROSS THE SCHOOL DAY</div><h2>A connected campus.<br/><em>One practical platform.</em></h2></div><p>Explore the workflows behind student records, academic planning, financial review, and supporting school services.</p></div><div className="product-module-grid">{schoolModules.map(m=>{const Icon=icons[m.icon];return <article className="product-module" key={m.title}><span className="service-icon"><Icon size={24} strokeWidth={1.5}/></span><h3>{m.title}</h3><p>{m.description}</p><ul>{m.details.map(d=><li key={d}>{d}</li>)}</ul></article>})}</div></div></section>
<section className="section container" id="results"><div className="section-heading"><div><div className="eyebrow">RESULTS WITH CHECKPOINTS</div><h2>Enter. Review.<br/><em>Publish with control.</em></h2></div><p>Marks entry and publication stay separate. Families see results only when the school makes them live.</p></div><ol className="result-flow">{[['Draft','Subject teachers save marks and grades.'],['Submitted','A complete section roster goes to the class teacher after the examination window.'],['Approved','The class teacher checks submissions and pass or fail decisions, or returns work for correction.'],['Live','The principal publishes validated sections; promotion and final-grade pass-out workflows follow.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
<section className="printing-section" id="printing"><div className="container"><div className="section-heading"><div><div className="eyebrow">DOCUMENTS FOR THE SCHOOL DAY</div><h2>Print formats.<br/><em>A clear view of availability.</em></h2></div><p>Fee-slip PDF printing is available today. The additional formats and editable template controls below are planned.</p></div><div className="print-grid">{schoolPrinting.map(p=><article key={p.title}><span className={`availability ${p.status==='Available'?'available':'planned'}`}>{p.status}</span><h3>{p.title}</h3><p>{p.description}</p></article>)}</div></div></section>
<section className="section container product-onboarding"><div><div className="eyebrow">GETTING YOUR SCHOOL SET UP</div><h2>Your records.<br/><em>Your school structure.</em></h2><p>Initial setup covers the agreed modules, roles, and dataset. Import-ready structured digital data takes 2–3 working days after complete data, required access, structure confirmation, and the advance are received. Document-based or unstructured data is assessed first, with no fixed completion deadline.</p></div><div className="onboarding-terms"><h3>A clear handover and support plan</h3><p>Basic training is included during the first calendar month from software handover. Three calendar months of maintenance is included from receipt of the advance. Further maintenance is invoiced separately at the agreed fee.</p><a href="/#contact" className="button button-dark">Plan your School Setu setup <Arrow diagonal/></a></div></section></main>}
