import {Arrow,ServiceIcon} from '@/components/ui';
import Services from '@/components/services';
import Contact from '@/components/contact';
import {company,faqs} from '@/lib/content';
import {Check,ArrowDown,Mail,Phone,MessageCircle,Plus} from 'lucide-react';
import SchoolPreview from '@/components/school-preview';
import Link from 'next/link';
export default function Home(){return <main id="main"><section className="hero"><div className="hero-grid-overlay"/><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/>YOUR NEXT DIGITAL CHAPTER</div><h1>Good ideas.<br/>Great <em>digital</em><br/>possibilities.</h1><p>From your first website to the software that runs your business. Bring your vision. We’ll help build what comes next.</p><div className="hero-actions"><a href="#contact" className="button button-gold">Start a conversation <Arrow diagonal/></a><a href="#services" className="text-link">Explore our services <Arrow/></a></div><div className="hero-foot"><span className="mini-symbol">✦</span>Thoughtfully designed. Built around you.</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orbit-node node-one"/><div className="orbit-node node-two"/><div className="hero-window"><div className="window-chrome"><span/><span/><span/><small>your-next-big-idea</small><span className="window-live">● In motion</span></div><div className="art-center"><div className="logo-tile"><img src="/lavener-symbol.png" alt="" width="73" height="83"/></div><div className="connector c-one"/><div className="connector c-two"/><div className="connector c-three"/><div className="art-label art-web"><ServiceIcon name="Globe" size={19}/><span>Web experiences</span></div><div className="art-label art-app"><ServiceIcon name="Smartphone" size={19}/><span>Mobile applications</span></div><div className="art-label art-erp"><ServiceIcon name="Layers" size={19}/><span>Connected operations</span></div></div><div className="art-code"><span>01</span> vision <b>→</b> design <b>→</b> development</div></div><div className="floating-card"><span className="floating-check"><Check size={19}/></span><div>From vision to reality.<small>Your next step starts here.</small></div></div><span className="art-coordinate">DESIGNED TO MOVE YOU FORWARD ↗</span></div></div><a href="#services" className="scroll-cue">A little further, a lot of possibility <ArrowDown size={14}/></a></section>
<div className="capability-strip"><div className="container">{['WEB & MOBILE','ERP & CRM','AI & AUTOMATION','DESIGN & GROWTH'].map(t=><span key={t}>{t}<i>✦</i></span>)}</div></div>
<section className="section services-section container" id="services"><div className="section-heading"><div><div className="eyebrow">01 / WHAT WE DO</div><h2>Different needs.<br/><em>One digital partner.</em></h2></div><p>Find the right starting point for your next project. Explore our services, then let’s shape the scope together.</p></div><Services/></section>
<section className="about-section" id="about"><div className="container about-grid"><div className="about-visual"><div className="about-ring"/><div className="about-monogram"><img src="/lavener-symbol.png" width="102" height="116" alt="Lavener symbol"/></div><span className="orbit-tag tag-discover">Discover</span><span className="orbit-tag tag-design">Design</span><span className="orbit-tag tag-build">Build</span><div className="about-caption">A clear path from<br/><strong>what if to what’s next.</strong></div></div><div className="about-copy"><div className="eyebrow">02 / MEET LAVENER</div><h2>Technology with<br/>your business<br/><em>at the centre.</em></h2><p>New development, existing-product maintenance, and IT consultancy, with agile planning and a focus on practical business needs.</p><div className="about-points"><span><Check size={17}/>Start with the problem</span><span><Check size={17}/>Make the scope clear</span><span><Check size={17}/>Build for everyday use</span></div><a href="#contact" className="text-link navy-link">Let’s get to know your idea <Arrow diagonal/></a></div></div></section>
<section className="section container school-section" id="school-setu"><div className="section-heading"><div><div className="eyebrow">03 / IN THE LAVENER FAMILY</div><h2>From admission<br/><em>to achievement.</em></h2></div><span className="pill">School Setu ERP</span></div><div className="school-showcase"><div className="school-copy"><span className="school-icon"><ServiceIcon name="GraduationCap" size={33}/></span><h3>School Setu</h3><p>One connected workspace for students, academics, campus teams, fees, and families.</p><ul><li>Principal, teacher, and parent portals</li><li>Academics, attendance, and results</li><li>Fees, payroll, and campus operations</li></ul><Link href="/school-setu" className="button button-dark">Explore School Setu <Arrow diagonal/></Link></div><div className="school-demo"><SchoolPreview/></div></div><div className="school-highlights">{[['Students & families','Admission records, documents, sibling links, and parent access.','Workflow'],['Academics & attendance','Curriculum, timetables, class diaries, and controlled exam results.','GraduationCap'],['Campus & finance','Collections, fee slips, payroll, library, transport, and reports.','Layers'],['The right access','Role-aware workspaces, branch switching, and activity logs.','Globe']].map(([title,description,icon])=><article key={title}><ServiceIcon name={icon} size={23}/><h3>{title}</h3><p>{description}</p></article>)}</div><div className="school-print-note"><span className="availability available">Fee slips available</span><p>Report-card, student ID, salary-slip, and custom-template printing are planned.</p><Link href="/school-setu#printing">See print formats <Arrow diagonal/></Link></div></section>
<section className="process-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">04 / HOW WE WORK</div><h2>Clear steps.<br/><em>Shared direction.</em></h2></div><p>You should always know what’s being built, why it matters, and what comes next.</p></div><div className="process-grid">{[['01','Plan together','Define requirements and agree on the scope.'],['02','Build with purpose','Turn the plan into working software.'],['03','Launch with confidence','Test, complete user acceptance, and deploy.']].map(([n,title,copy])=><article key={n}><div className="process-number">{n}<Arrow/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="section container faq-section"><div><div className="eyebrow">05 / A FEW GOOD QUESTIONS</div><h2>Before we<br/><em>get started.</em></h2><a href={`mailto:${company.email}`} className="text-link navy-link">Ask us something else <Arrow diagonal/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
<section className="contact-section" id="contact"><div className="container contact-grid"><div className="contact-copy"><div className="eyebrow">06 / LET’S MAKE IT HAPPEN</div><h2>Your next chapter<br/><em>starts with hello.</em></h2><p>Tell us about your business, your school, or the idea you can’t stop thinking about.</p><div className="contact-links"><a href={`mailto:${company.email}`}><Mail size={21}/><span><small>WRITE TO US</small>{company.email}</span><Arrow diagonal/></a><a href={`tel:${company.tel}`}><Phone size={21}/><span><small>GIVE US A CALL</small>{company.phone}</span><Arrow diagonal/></a><a href={`https://wa.me/${company.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={21}/><span><small>KEEP IT SIMPLE</small>Say hello on WhatsApp</span><Arrow diagonal/></a></div></div><Contact/></div></section></main>}
