export const company = { name: 'Lavener Holdings', email: 'lavenergroup@gmail.com', phone: '+91 7011335800', tel: '+917011335800', whatsapp: '917011335800', gstin: '07AJEPF6326P1ZX' };
export const services = [
  { slug:'web-development', title:'Websites & portals', category:'Build', icon:'Globe', summary:'A better home for your business online.', description:'Business websites and web portals built around your customers, content, and day-to-day needs.', tags:['Next.js','React','WordPress'], deliverables:['Responsive page design','Content and navigation structure','Web portal workflows','Launch and handover'] },
  { slug:'app-development', title:'Mobile applications', category:'Build', icon:'Smartphone', summary:'Your idea. In the palm of their hand.', description:'Mobile experiences for iOS and Android, with native or cross-platform development.', tags:['Flutter','Kotlin','React Native'], deliverables:['App experience design','Mobile development','Testing and release planning','Application maintenance'] },
  { slug:'crm-development', title:'CRM & automation', category:'Operate', icon:'Workflow', summary:'Less busywork. More business.', description:'Custom CRM workflows for customer relationships, business decisions, and operational automation.', tags:['CRM','MERN','Automation'], deliverables:['Workflow discovery','CRM configuration','Roles and reporting','Data setup and handover'] },
  { slug:'erp-solutions', title:'ERP solutions', category:'Operate', icon:'Layers', summary:'Bring your everyday operations together.', description:'Connected software for school records, academics, attendance, fees, payroll, and families through School Setu ERP.', tags:['School Setu','ERP','Data setup'], deliverables:['Agreed module setup','Initial data import','User roles and access','Basic training and support'] },
  { slug:'ai-ml', title:'AI & machine learning', category:'Build', icon:'Sparkles', summary:'Turn a complex problem into a useful tool.', description:'Python-based AI solutions for practical use cases across industries.', tags:['Python','AI','Machine learning'], deliverables:['Use-case assessment','Data readiness review','Prototype and evaluation','Integration planning'] },
  { slug:'learning-platforms', title:'Learning platforms', category:'Operate', icon:'GraduationCap', summary:'Make learning easier to manage.', description:'Moodle and custom learning platforms for course delivery and syllabus tracking.', tags:['Moodle','LMS','Custom platforms'], deliverables:['Course structure','Learner and staff roles','Learning workflows','Platform setup'] },
  { slug:'digital-marketing', title:'Digital marketing', category:'Grow', icon:'TrendingUp', summary:'Help the right people find you.', description:'Search visibility and digital campaigns for business growth.', tags:['SEO','Campaigns','Content'], deliverables:['Website visibility review','Campaign planning','Content direction','Performance reporting'] },
  { slug:'ui-ux-design', title:'UI & UX design', category:'Build', icon:'PenTool', summary:'Good design makes everything feel simpler.', description:'Interface design and user journeys that make digital products easier to understand.', tags:['Research','UI design','Prototypes'], deliverables:['User flow mapping','Wireframes','Visual interface design','Interactive prototypes'] },
] as const;
export const faqs = [
 ['How do I get a project estimate?', 'Tell us what you want to build. We will discuss the scope and send a quotation.'],
 ['Can you work on an existing product?', 'Yes. Share the current setup and the changes you need, and we can discuss development, maintenance, or consultancy.'],
 ['Which technologies do you work with?', 'Our services cover JavaScript, Python, MERN, mobile development, and learning platforms. The stack depends on your project.'],
 ['What can School Setu help our school manage?', 'Student records, curriculum, timetables, attendance, exams and results, fees, staff payroll, library, transport, notices, and reports. Principal, teacher, and parent portals provide role-aware access.'],
 ['Which School Setu print formats are available?', 'A4 fee-slip PDFs are available. Report-card, student ID-card, salary-slip, and custom-template printing are planned and are not yet available.'],
 ['What setup and support is included with School Setu?', 'The agreed ERP modules, initial data setup, and basic training during the first month from handover. Three months of included maintenance starts when the advance payment is received. Scope and later maintenance charges are agreed in writing.'],
];
