export const schoolModules = [
  {title:'Admissions and student records',icon:'Users',description:'Keep admission and roll numbers, personal details, family contacts, previous school history, board IDs, documents, and sibling links together.',details:['Birth and transfer certificates, prior report cards, disability and reservation documents','Section-transfer requests with approval or rejection','Enrollment, final-result promotion, transfer, and pass-out workflows']},
  {title:'Classes and curriculum',icon:'BookOpen',description:'Organise grades, sections, rooms, class teachers, and subjects in one academic structure.',details:['Grade-specific syllabus chapters, topics, and terms','Library books linked to curriculum subjects','Weekly lecture targets and preferred teaching periods']},
  {title:'Timetables and scheduling',icon:'CalendarDays',description:'Generate schedules using teacher availability, subject requirements, and period preferences, then review and edit them.',details:['Working days, named periods, times, and breaks','Conflict resolution and lesson distribution during generation','Shared class, teacher, and parent timetable views']},
  {title:'Student attendance',icon:'ClipboardCheck',description:'Class teachers record present, absent, late, leave, and half-day statuses for assigned classes and sections.',details:['Recorded-day history and attendance summaries','Attendance rates for school review','Monthly calendars and overall attendance for parents']},
  {title:'Staff attendance and payroll',icon:'Wallet',description:'Review location-aware mobile check-in and check-out alongside monthly salaries and late deductions.',details:['School radius, working hours, grace periods, and late rules','Fixed or percentage deductions and administrative correction','Employee profiles, base salary, gross payroll, and net payable summaries']},
  {title:'Exams and academic progression',icon:'GraduationCap',description:'Keep exam planning, teacher marks entry, class-teacher review, and principal publication separate.',details:['Academic years, exam sessions, marks, and datesheets','Draft, submitted, approved, and live result states','Passing-student promotion and final-grade pass-out processing']},
  {title:'Fees and collections',icon:'Receipt',description:'Set grade-wise monthly fees, additional charges, concessions, and discounts; record payments and review what is due.',details:['Cash, UPI, card, cheque, and bank-transfer recording','UPI reference numbers, paid months, and transaction history','Paid, pending or upcoming, and overdue status with printable fee slips']},
  {title:'Library catalogue',icon:'Library',description:'Maintain book titles, authors, ISBNs, categories, and copy counts.',details:['Central catalogue of library records','Books connected to grade-specific subjects','Curriculum links for academic planning']},
  {title:'Transport routes',icon:'Bus',description:'Maintain the route and vehicle information used by the school.',details:['Route names and vehicle numbers','Driver details and vehicle capacity','Student transport mode and pickup contact records']},
  {title:'Class diary and notices',icon:'Megaphone',description:'Share daily teaching information and relevant school or class announcements with families.',details:['Topics taught, classwork, homework, and teacher remarks','Notices, meetings, events, and exam messages','Parent access to diary entries and child-relevant announcements']},
  {title:'Reports and activity logs',icon:'BarChart3',description:'Review school totals, collection status, attendance rankings, and supported user activity.',details:['Student, teacher, class, and collection summaries','At-risk students and overdue charges','Read-only logs with actor, role, time, entity, and action details']},
  {title:'Branches, settings, and access',icon:'ShieldCheck',description:'Principals can switch active branches and control administrative areas using fourteen permission keys.',details:['School and branch details, contacts, academic year, and working days','Branch-separated school records','Role-aware principal, teacher, and linked-parent access']},
] as const;

export const schoolPortals = [
  {id:'principal',title:'Principal',label:'A clearer view of the school',description:'A responsive desktop and web workspace for school leadership, academics, finance, and campus teams.',features:[['School overview','Active students, teachers, classes, announcements, and fee-collection status.'],['Performance and trends','Weekly attendance, grade-band distribution, and recorded student performance.'],['Academic control','Manage structures, timetables, exam schedules, result publication, and progression.'],['Campus administration','Review staff, payroll, library, transport, settings, reports, and audit activity.'],['Financial visibility','See collected, pending, and overdue charges together.'],['Branch and permission controls','Switch active branches and manage access to administrative areas.']]},
  {id:'teacher',title:'Teacher',label:'The educator’s working day',description:'A dedicated web and mobile experience for assigned classes, daily teaching, and self-service.',features:[['Daily dashboard','Teaching schedule, assigned classes, student counts, and current notices.'],['Class rosters','Student and emergency contact information for assigned sections.'],['Attendance and diary','Record student attendance, topics taught, classwork, homework, and remarks.'],['Marks and review','Save draft subject marks and submit complete rosters; class teachers review results.'],['Personal timetable','Weekly class and period information from the shared school schedule.'],['Mobile self-service','Location-aware check-in and check-out, plus email OTP password reset.']]},
  {id:'parent',title:'Parent',label:'Stay close to each child’s progress',description:'A mobile-first experience with child switching and access limited to linked student records.',features:[['Linked children','Switch among children connected to one parent account.'],['Attendance calendar','View overall attendance, present days, and month-by-month records.'],['Published results','See subject marks, grades, and remarks after school publication.'],['Fees and payment history','Review monthly and additional charges, due status, and payment records.'],['Diary and learning','Read homework, classwork, notes, timetables, and syllabus chapters.'],['Relevant announcements','School-wide and class-specific notices, meetings, events, and exam messages.']]},
] as const;

export const schoolPrinting = [
  {title:'Fee slips',status:'Available',description:'Designed A4 PDFs for one paid month or all months in a transaction, using school, student, and payment details.'},
  {title:'Report cards',status:'Planned',description:'School-branded result sheets with exam sessions, marks, grades, remarks, and approval or signature areas.'},
  {title:'Student ID cards',status:'Planned',description:'Compact layouts with school branding, student photo, admission number, class, and selected contacts.'},
  {title:'Salary slips',status:'Planned',description:'Employee and pay-period details with salary, attendance, deductions, and net payable amounts.'},
  {title:'Custom print templates',status:'Planned',description:'Controls for school logos, colours, fields, page dimensions, and signature areas.'},
] as const;
